name: \art 2018
description: Blogging about the creative process
meta_description: "\\art 2018"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 10
baseurl: /
domain_name: 'http://backslashart.github.io'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://backslashart.github.io'
author:         'Christy Cui, Jacob Lee'