name: \art 2018
description: Blogging about the creative process
meta_description: "\\art 2018"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl: /
domain_name: 'http://backslashart.github.io'
plugins: [jekyll-paginate]
timezone: America/New_York

# Details for the RSS feed generator
url:            'http://backslashart.github.io'
author:         'Christy Cui, Jacob Lee'